### ISSUE TITLE
Add Carousel Component

### ISSUE THREAD

**Issue by Ohswedd** [altxriainc/kromacss#2]
Develop a new Carousel component to enhance the framework's functionality for displaying a series of images, cards, or other elements in a sliding format. The component should support both auto-play and manual controls, be responsive, and work seamlessly in both light and dark modes. Additionally, consider adding customization options for transition effects, timing, and navigation controls (e.g., arrows, dots).

**Comment by IamLRBA** [comment]
@Ohswedd may i be assigned this issue. Thanks!

**Comment by Ohswedd** [comment]
> @Ohswedd may i be assigned this issue. Thanks!

Sure, feel free to contribute without any problem. Just work on the component and send a PR, it will be our job to review it. Make sure you follow the guidelines of our framework and how the other components were built, always check the demo. Thank you for the interest in our project!
